social/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('topic/<int:id>/posts/',views.PostListView.as_view(),name='post_list'),
    path('topic/<int:id>/posts/<int:post_id>/',views.PostDetailView.as_view(),name='post_detail'),
    path('topic/<int:id>/posts/<int:post_id>/create_comment',views.CommentCreateView.as_view(),name='comment_create'),
    path('topic/<int:id>/create_post/',views.PostCreateView.as_view(),name='post_create'),
    path('topic/<int:id>/edit_post/<int:post_id>',views.PostUpdateView.as_view(),name='post_edit'),
    path('delete_comment/<int:comment_id>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('drafts/',views.DraftListView.as_view(),name='posts_draft'),
    path('edit_comment/<int:comment_id>',views.CommentUpdateView.as_view(),name='comment_edit'),
    path('delete_post/<int:post_id>',views.PostDeleteView.as_view(),name='post_delete'),
    path('topics/',views.TopicListView.as_view(),name='topics'),
    path('joinUserToTopic/<int:topic_id>',views.JoinTopic.as_view(),name='join_topic'),
    path('removeUserFromTopic/<int:topic_id>',views.LeaveTopic.as_view(),name='remove_from_topic'),
    path('newTopic/',views.TopicCreateView.as_view(),name='new_topic'),
    path('resources/',views.ResourcesView.as_view(),name='resources'),
]

spaceSocialMedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accounts.urls','accounts'),namespace='accounts')),
    path('social/',include(('social.urls','social'),namespace='social')),
]

social/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import *
from django.utils import timezone
from django.urls import reverse
from django import template
register = template.Library()

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='author')
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE,related_name='topic')
    title = models.CharField(max_length=30,blank=False)
    is_published = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)
    content = models.TextField(default='')

    def save(self):
        if self.is_published:
            self.published_date = timezone.now()
        return super().save()

    def get_absolute_url(self):
        return reverse("social:detail", kwargs={"id": self.pk})
    
    def __str__(self):
        return self.author.username

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    comment_author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment_author')
    comment_created_date = models.DateTimeField(auto_now=True)
    comment_content = models.TextField(default='')

    def __str__(self):
        return self.comment_author.username

    def get_absolute_url(self):
        return reverse("social:detail", kwargs={"id": self.post.pk})
    

social/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView,RedirectView
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.generic import ListView, CreateView, DeleteView,RedirectView
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import *
from django.contrib.auth.models import User, Permission
from accounts.models import *
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages


login_url = 'accounts:login'

class JoinTopic(LoginRequiredMixin,RedirectView):
    login_url = login_url

    def get_redirect_url(self, *args, **kwargs):
        return reverse("social:topics")
    
    def get(self, request, *args, **kwargs):
        topic = get_object_or_404(Topic,pk=kwargs.get('topic_id'))
        user = get_object_or_404(User,pk=request.user.pk)
        if not user.groups.filter(name = topic.name).exists():
            topic.user_set.add(user)
            messages.success(self.request,f"You joined {topic.name}!")
        else:
            messages.warning(self.request,f"You already joined {topic.name}!")
        return super().get(request, *args, **kwargs)

class LeaveTopic(LoginRequiredMixin,RedirectView):
    login_url = login_url
    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:profile",kwargs={'id':self.request.user.pk})
    
    def get(self, request, *args, **kwargs):
        topic = get_object_or_404(Topic,pk=kwargs.get('topic_id'))
        user = get_object_or_404(User,pk=request.user.pk)
        if user.groups.filter(name = topic.name).exists():
            topic.user_set.remove(user)
            messages.success(self.request,f"You leaved {topic.name}!")
        else:
            messages.warning(self.request,f"You are not in this {topic.name}!")
        return super().get(request, *args, **kwargs)

class ResourcesView(TemplateView):
    template_name = 'social/resources_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Resources'
        return context
    

class TopicCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Topic
    permission_required = ('accounts.add_topic')
    template_name = "social/topic_create.html"
    fields = ('name','description')
    login_url = login_url
    def form_valid(self,form):
        topic = form.save()
        social_permissions = Permission.objects.filter(content_type__app_label='social').values('id')
        topic.permissions.add(social_permissions)
        topic.save()
        return HttpResponseRedirect(reverse('social:post_list',kwargs={'id':topic.id}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "New Topic"
        return context
    


class HomeView(TemplateView):
    template_name = 'social/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home"
        return context

class CommentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Comment
    template_name = "social/comment_create.html"
    permission_required = ('social.add_comment')
    fields = ('comment_content',)
    login_url = login_url
    def form_valid(self, form):
        user = get_object_or_404(User, pk=self.request.user.pk)
        post = get_object_or_404(Post, id=self.kwargs['post_id'])
        comment = form.save(commit=False)
        comment.comment_author = user
        comment.post = post
        comment.save()
        return HttpResponseRedirect(reverse('social:post_detail', kwargs={'id': self.kwargs['id'], 'post_id': post.id}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "New comment"
        return context


class CommentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Comment
    template_name = "social/comment_delete.html"
    permission_required = ('social.delete_comment')
    slug_field = 'id'
    slug_url_kwarg = 'comment_id'
    login_url = login_url
    def get_success_url(self):
        return reverse_lazy('social:post_detail', kwargs={'id': self.get_object().post.topic.pk, 'post_id': self.get_object().post.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete Comment"
        return context


class CommentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = "social/comment_update.html"
    permission_required = ('social.change_comment')
    slug_field = 'id'
    slug_url_kwarg = 'comment_id'
    fields = ('comment_content',)
    login_url = login_url
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Edit Comment"
        return context

    def get_success_url(self):
        return reverse_lazy('social:post_detail', kwargs={'id': self.get_object().post.topic.pk, 'post_id': self.get_object().post.id})

class TopicListView(LoginRequiredMixin,ListView):
    model = Topic
    template_name = 'social/topics_list.html'
    context_object_name = 'topics'
    login_url = login_url

class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('social.change_post')
    model = Post
    template_name = 'social/post_edit.html'
    slug_field = 'id'
    slug_url_kwarg = 'post_id'
    fields = ('title', 'content','is_published')
    login_url = login_url
    def get_success_url(self):
        return reverse('social:post_detail', kwargs=self.kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f'Edit {self.get_object().title}'
        return context


class PostDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = ('social.view_post')
    model = Post
    template_name = "social/post_detail.html"
    slug_field = 'id'
    slug_url_kwarg = 'post_id'
    context_object_name = 'post'
    login_url = login_url
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(
            post=self.get_object())
        context['topic_id'] = self.kwargs['id']
        context["title"] = self.get_object().title
        return context


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Post
    template_name = "social/post_create.html"
    permission_required = ('social.add_post')
    fields = ('title', 'content')
    login_url = login_url
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Create Post"
        return context

    def publish(self):
        return 'Publish' in self.request.POST

    def form_valid(self, form):
        topic = get_object_or_404(Topic, pk=self.kwargs['id'])
        user = get_object_or_404(User, pk=self.request.user.pk)
        post = form.save(commit=False)
        post.author = user
        post.is_published = self.publish()
        post.topic = topic
        post.save()
        return HttpResponseRedirect(reverse('social:post_detail', kwargs={'id': self.kwargs['id'], 'post_id': post.id}))


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Post
    template_name = "social/post_delete.html"
    permission_required = ('social.delete_post')
    slug_field = 'id'
    slug_url_kwarg = 'post_id'
    login_url = login_url
    context_object_name = "post"
    def get_success_url(self):
        return reverse_lazy('accounts:profile', kwargs={'id': self.request.user.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Delete {self.object.title}"
        return context
    
    

class DraftListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = "social/post_list.html"
    permission_required = ('social.view_post','social.change_post')
    context_object_name = 'posts'
    login_url = login_url
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Drafts'
        return context

    def get_queryset(self):
        return Post.objects.filter(author = self.request.user,is_published=False)
    

class PostListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Post
    template_name = "social/post_list.html"
    permission_required = ('social.view_post')
    context_object_name = 'posts'
    login_url = login_url
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['topic_id'] = self.kwargs['id']
        context['title'] = "Posts"
        return context

    def get_queryset(self):
        topic = get_object_or_404(Topic, pk=self.kwargs['id'])
        return Post.objects.filter(topic=topic, is_published=True)

templates/social/comment_create.html
{%extends '../base.html'%}
{% load bootstrap3 %}

{%block content%}
<div class="container">
    <form id="create_post" method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" class='btn' value="Publish">        
    </form>
</div>
{%endblock%}

templates/social/comment_delete.html
{%extends '../base.html'%}

{%block content%}
<div class="container">
    <h3>Do you really want to delete this comment?</h3>
    <form id="delete_post" method="post">
        {%csrf_token%}
        {{ form.as_p }}
        <input type="submit" class='btn btn-danger' value="Delete">
        <div class="display-inline">
            <a class = "btn btn-primary" href="{% url 'social:post_detail' post_id=object.post.id id=object.post.topic.id %}">Cancel</a>
        </div>
    </form>
</div>
{%endblock%}

templates/social/comment_update.html
{%extends '../base.html'%}
{% load bootstrap3 %}

{%block content%}
<div class="container">
    <form id="create_post" method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" class='btn' value="Change">        
    </form>
</div>
{%endblock%}

templates/social/home.html
{%extends '../base.html'%}

{%block content%}
<div id="content" class="left-align roboto">
    <p class='title'>
        Space Social Media
    </p>
    <hr>
    <p class="text-justify">
        Here you can write about Space, join Groups and More!
    </p>
    <p class="text-justify">
        If you wish to join <a href="#" class="text-decoration-none">sign-up</a> <strong>now</strong>!
    </p>
</div>
{%endblock%}

templates/social/post_create.html
{%extends '../base.html'%}
{% load bootstrap3 %}

{%block content%}
<div class="container">
    <form id="create_post" method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" class='btn' name="Publish" value="Publish">
        <input type="submit" class='btn' name="Save" value="Save">
    </form>
</div>
{%endblock%}

templates/social/post_delete.html
{%extends '../base.html'%}

{%block content%}
<div class="container">
    <h3>Do you really want to delete this post?</h3>
    <form id="delete_post" method="post">
        {%csrf_token%}
        {{ form.as_p }}
        <input type="submit" class='btn btn-danger' value="Delete">
        <div class="display-inline">
            <a class = "btn btn-primary" href="{% url 'social:post_detail' post_id=post.id id=post.topic.id %}">Cancel</a>
        </div>
    </form>
</div>
{%endblock%}

templates/social/post_detail.html
{%extends '../base.html'%}

{%block content%}
<div id="detail-content" class="container roboto">
    <div class="flex-direction-column">
        <div class="post-header">
            <h1 class="roboto">{{post.title}}</h1>
            <p class="font-italic">{{post.author}}</p>
        </div>
        <div id='conteudo' class='text-wrap'>{{post.content|safe}}</div>
        {%if user == post.author %}
        <div class="row-reverse">
            <a class='btn btn-danger' href="{%url 'social:post_delete' post_id=post.id%}">
                <i class="fas fa-trash-alt"></i>
            </a>
            <a class='btn btn-success' href="{%url 'social:post_edit' post_id=post.id id=post.topic_id%}">
                <i class="fas fa-edit"></i>
            </a>
        </div>
        {%endif%}
    </div>
    <div class="row-reverse">
        <a href="{%url 'social:comment_create' post_id=post.id id=topic_id%}" class="btn btn-primary">Comment</a>
    </div>
    <div class="wrapper">
        {%if comments%}
            <h3 class="roboto">Comments</h3>
            <hr style="background-color: white;">
        {% endif %}
        <ul class="list-group">
            {%for comment in comments%}
            <li class="list-group-item">
                <div class='justify-content-center html-inside'>
                    <p class="roboto">{{comment.comment_content|safe}}</p>
                </div>
                <p class="font-italic roboto">{{comment.comment_author}}</p>
                {%if comment.comment_author == user%}
                <a class='btn btn-success' href="{%url 'social:comment_edit' comment_id=comment.id%}">
                    <i class="fas fa-edit"></i>
                </a>
                <a class='btn btn-danger' href="{%url 'social:comment_delete' comment_id=comment.id%}">
                    <i class="fas fa-trash-alt"></i>
                </a>
                {%endif%}
            </li>
            {%endfor%}
        </ul>
    </div>
</div>
{%endblock%}

templates/social/post_edit.html
{%extends '../base.html'%}
{% load bootstrap3 %}

{%block content%}
<div class="container">
    <form id="edit_post" method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" class='btn' value="Commit Changes">
    </form>
</div>
{%endblock%}

templates/social/post_list.html
{%extends '../base.html'%}
{%load social_tags%}
{%block content%}
<div id="content" class="left-align roboto container">
    {%if posts%}
    <div class="list-group">
        {%for post in posts%}
        <a href="{%url 'social:post_detail' post_id=post.pk id=post.topic.pk%}"
            class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 font-weight-light">{{post.title}}</h5>
                {%if post.published_date%}
                <small>{{post.published_date| daysCount}} days ago</small>
                {%endif%}
            </div>
            <p class="mb-1 font-italic">{{post.author}}</p>
            <small>Posted in {{post.published_date| date:"d-m-Y h:i"}}</small>
        </a>
        {%endfor%}
    </div>
    {%endif%}
    {%if topic_id and posts%}
    <div class="margin-top justify-content-flex-end">
        <a class="btn btn-primary" href="{%url 'social:post_create' id=topic_id%}">
            <i class="far fa-plus-square"></i>
        </a>
    </div>
    {%elif topic_id%}
    <div class='container roboto'>
        <h2>Sorry, we are without posts!</h2>
        <a class='text-decoration-none' href="{%url 'social:post_create' id=topic_id%}">
            <p>Feel free to create one <i class="fas fa-arrow-circle-right"></i></p>
        </a>
    </div>
    {%endif%}
    {%if not posts and not topic_id%}
    <div class='container roboto'>
        <h2>You do not have any drafts!</h2>
    </div>
    {%endif%}
</div>
{%endblock%}

templates/social/resources_view.html
{% extends '../base.html' %}

{%block content%}
<div id='resources' class="container">
    <div class="margin-top list-group">
        <a href="https://codepen.io/kowlor/pen/ZYYQoy" target='_blank'
            class="list-group-item list-group-item-action roboto">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Solar System Backgroud</h5>
                <small>Made By: Malik Dellidj - @Dathink</small>
            </div>
            <p class="mb-1">This background is amazing, thanks to Malik</p>
            <p class="mb-1">See more <i class="fas fa-plus-circle"></i></p>
        </a>
        <a href="https://fontawesome.com/" target='_blank'
            class="list-group-item list-group-item-action roboto">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Used Icons</h5>
            </div>
            <p class="mb-1">Thanks fontawsome for providing such <strong>awsome icons</strong></p>
            <p class="mb-1">See more <i class="fas fa-plus-circle"></i></p>
        </a>
        <a href="https://github.com/yabwe/medium-editor" target='_blank'
            class="list-group-item list-group-item-action roboto">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">Medium Editor</h5>
            </div>
            <p class="mb-1">Thanks to everyone in this amazing community who worked on this inline editor, they rocked!</p>
            <p class="mb-1">See more <i class="fas fa-plus-circle"></i></p>
        </a>
    </div>
</div>
{% endblock %}

templates/social/topic_create.html
{%extends '../base.html'%}
{% load bootstrap3 %}

{%block content%}
<div class="container">
    <form id="create_topic" method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
    <input type="submit" class='btn' value="Create">
</form>
</div>
{%endblock%}

templates/social/topics_list.html
{%extends '../base.html'%}
{%load social_tags%}
{%block content%}
<div id="content" class="left-align roboto container">
    <div id="topics-list" class="list-group">
        {%for topic in topics%}
        <a href="{% url 'social:join_topic' topic_id=topic.pk%}"
            class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{topic.name}}</h5>
                <small>Since {{topic.creation_date|daysCount}} days</small>
            </div>
            <p class="mb-1">{{topic.description|safe}}</p>
            <p class="mb-1">Join <i class="fas fa-plus-circle"></i></p>
            <small>Users: {{topic.user_set.all.count}}</small>
        </a>
        {%endfor%}
    </div>
</div>
{%endblock%}