accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.SignUpView.as_view(),name='home'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('profile/<int:id>/',views.ProfileView.as_view(),name='profile'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
]

social/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('topic/<int:id>/posts/',views.PostListView.as_view(),name='post_list'),
    path('topic/<int:id>/posts/<int:post_id>/',views.PostDetailView.as_view(),name='post_detail'),
    path('topic/<int:id>/posts/<int:post_id>/create_comment',views.CommentCreateView.as_view(),name='comment_create'),
    path('topic/<int:id>/create_post/',views.PostCreateView.as_view(),name='post_create'),
    path('topic/<int:id>/edit_post/<int:post_id>',views.PostUpdateView.as_view(),name='post_edit'),
    path('delete_comment/<int:comment_id>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('drafts/',views.DraftListView.as_view(),name='posts_draft'),
    path('edit_comment/<int:comment_id>',views.CommentUpdateView.as_view(),name='comment_edit'),
    path('delete_post/<int:post_id>',views.PostDeleteView.as_view(),name='post_delete'),
    path('topics/',views.TopicListView.as_view(),name='topics'),
    path('joinUserToTopic/<int:topic_id>',views.JoinTopic.as_view(),name='join_topic'),
    path('removeUserFromTopic/<int:topic_id>',views.LeaveTopic.as_view(),name='remove_from_topic'),
    path('newTopic/',views.TopicCreateView.as_view(),name='new_topic'),
    path('resources/',views.ResourcesView.as_view(),name='resources'),
]

spaceSocialMedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accounts.urls','accounts'),namespace='accounts')),
    path('social/',include(('social.urls','social'),namespace='social')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.urls import reverse
from django import template
register = template.Library()
class Topic(Group):
    description = models.CharField(max_length=50)
    creation_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("social:post_list", kwargs={"id": self.pk})
    

accounts/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import RedirectView
from django.contrib.auth import logout,authenticate,login
from django.http import HttpResponseRedirect,HttpResponseForbidden
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
class SignUpView(CreateView):
    template_name = "accounts/home.html"
    form_class = UserCreationForm
    model = User

    def get_success_url(self):
        user = authenticate(self.request,username=self.request.POST.get('username'),password=self.request.POST.get('password1'))
        login(self.request,user=user)
        return reverse('accounts:profile',kwargs={'id':self.request.user.pk})

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('accounts:profile',kwargs={'id':request.user.pk}))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Home"
        return context

class UserLoginView(SuccessMessageMixin,LoginView):
    template_name = 'accounts/login.html'    
    success_message = "Well Done! You are in!"

    def get_success_url(self):
        return reverse('accounts:profile',kwargs={'id':self.request.user.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Login"
        return context

class UserLogoutView(RedirectView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('accounts:home')) 

class ProfileView(LoginRequiredMixin,DetailView):
    context_object_name = 'user'
    model = User
    slug_field = 'id'
    slug_url_kwarg = 'id'
    template_name = 'accounts/profile.html'
    login_url = 'accounts:login'
    current_user = None

    def get(self, request, *args, **kwargs):
        if self.get_object().pk != request.user.pk:
          return HttpResponseForbidden(content='Hey! This is not your profile!')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = context['user'].username
        return context
    

templates/accounts/home.html
{%extends '../base.html'%}
{%load bootstrap3%}

{%block content%}
<div id="content" class="left-align roboto flex-row row">
    <div class="font-white wrapper flex-column-grow col-medium-6">
        <p class='title'>
            Space Social Media
        </p>
        <hr>
        <p class="text-justify">
            Here you can write about Space, join Groups and More!
        </p>
        <p class="text-justify">
            If you wish to join sign-up <strong>now</strong>!
        </p>
    </div>
    <div class='justify-content-right col-lg-6' id="form-content">
        <div class='justify-content-right row-reverse fade-in'>
            <form method="post" id="form-home">
                {%csrf_token%}
                {% bootstrap_form form %}
                <input type="submit" class='btn btn btn-light' value="Sign-Up">
            </form>
        </div>
    </div>
</div>
{%endblock%}

templates/accounts/login.html
{%extends '../base.html'%}
{% load bootstrap3 %}
{%block content%}
<div id="content" class="container">
    <form method="post">
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" value="Login">
    </form>
</div>
{%endblock%}

templates/accounts/profile.html
{%extends '../base.html'%}

{%block content%}
<h1 id="username_display" class='fade-in font-italic roboto'>{{user}}</h1>
<div class="container">
    <h3 class="text-left roboto">Your Joined Topics</h3>
    <div id="profile-content" class="justify-content-center">
        <div class="row roboto flexed medium-size container">
            {%for group in user.groups.all%}
            <a class='detail-link' href="{%url 'social:post_list' id=group.pk%}">
                <div class="card margin-bottom group-desc col-md-4 margin-right">
                    <div class="card-body">
                        <div class="card-title">
                            {{group.name}}
                        </div>
                        <div class="card-text">Users: {{group.user_set.all.count}}</div>
                        <small>Read Posts</small>
                        <a href="{%url 'social:remove_from_topic' topic_id=group.pk%}"
                            class="btn btn-danger float-right"><i class="fas fa-trash-alt"></i></a>
                    </div>
                </div>
            </a>
            {%endfor%}
        </div>
    </div>
</div>
{%endblock%}