accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.SignUpView.as_view(),name='home'),
    path('login/',views.UserLoginView.as_view(),name='login'),
    path('profile/<int:id>/',views.ProfileView.as_view(),name='profile'),
    path('logout/',views.UserLogoutView.as_view(),name='logout'),
]

social/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('topic/<int:id>/posts/',views.PostListView.as_view(),name='post_list'),
    path('topic/<int:id>/posts/<int:post_id>/',views.PostDetailView.as_view(),name='post_detail'),
    path('topic/<int:id>/posts/<int:post_id>/create_comment',views.CommentCreateView.as_view(),name='comment_create'),
    path('topic/<int:id>/create_post/',views.PostCreateView.as_view(),name='post_create'),
    path('topic/<int:id>/edit_post/<int:post_id>',views.PostUpdateView.as_view(),name='post_edit'),
    path('delete_comment/<int:comment_id>',views.CommentDeleteView.as_view(),name='comment_delete'),
    path('drafts/',views.DraftListView.as_view(),name='posts_draft'),
    path('edit_comment/<int:comment_id>',views.CommentUpdateView.as_view(),name='comment_edit'),
    path('delete_post/<int:post_id>',views.PostDeleteView.as_view(),name='post_delete'),
    path('topics/',views.TopicListView.as_view(),name='topics'),
    path('joinUserToTopic/<int:topic_id>',views.JoinTopic.as_view(),name='join_topic'),
    path('removeUserFromTopic/<int:topic_id>',views.LeaveTopic.as_view(),name='remove_from_topic'),
    path('newTopic/',views.TopicCreateView.as_view(),name='new_topic'),
    path('resources/',views.ResourcesView.as_view(),name='resources'),
]

spaceSocialMedia/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accounts.urls','accounts'),namespace='accounts')),
    path('social/',include(('social.urls','social'),namespace='social')),
]

templates/partial/messages.html
{%if messages%}
<div class="d-flex justify-content-end">
    {%for message in messages%}
        <div class="alert {{message.tags}} fade-in margin-right" role="alert">
            <h5 class='alert-heading'>{{message}}</h5>
        </div>
    {% endfor %}
</div>
{%endif%}

templates/partial/navbar.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark">
        {%if user.is_authenticated%}
            <a class="roboto navbar-brand" href="{%url 'accounts:profile' id=user.id%}">Social Space</a>
        {%else%}
            <a class="roboto navbar-brand" href="{%url 'accounts:home'%}">Social Space</a>
        {%endif%}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="roboto nav-link" href="{%url 'social:resources'%}">Resources</a>
                </li>
                <li class="nav-item active">
                    <a class="roboto nav-link" target= "_blank" href="https://github.com/duccl/space-social-media">Github</a>
                </li>
                <li class="nav-item active">
                    <a class="roboto nav-link" href="{%url 'social:topics'%}">Topics</a>
                </li>
                {%if topic_id%}
                <li class="nav-item">
                    <a class="roboto nav-link" href="{%url 'social:post_create' id=topic_id%}">New Post</a>
                </li>
                {%endif%}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="roboto nav-link" href="{%url 'social:new_topic'%}">New Topic</a>
                    </li>
                    <li class="nav-item">
                        <a class="roboto nav-link" href="{%url 'social:posts_draft'%}">Drafts</a>
                    </li>
                {%endif%}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="roboto nav-link" href="{%url 'accounts:profile' id=user.pk%}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="roboto nav-link" href="{%url 'accounts:logout'%}">Logout</a>
                </li>
                {%else%}
                <li class="nav-item active">
                    <a class="roboto nav-link" href="{%url 'accounts:login'%}">Login</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </nav>
</header>